# http://travis-ci.org/#!/ipython/ipython
language: python

cache:
    directories:
        - $HOME/.cache/bower
python:
    - 3.5.1  # Set to 3.5.1 since travis has not yet included as default for 3.5
    - 2.7

sudo: false

env:
  global:
    - PATH=$TRAVIS_BUILD_DIR/pandoc:$PATH
  matrix:
    - GROUP=js/notebook
    - GROUP=python
    - GROUP=js/base
    - GROUP=js/services
    - GROUP=js/tree

before_install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools wheel nose coverage codecov
    - nvm install 6.9.2
    - nvm use 6.9.2
    - node --version
    - npm --version
    - npm upgrade -g npm
    - npm install
    - |
      if [[ $GROUP == js* ]]; then 
        npm install -g casperjs@1.1.3 phantomjs-prebuilt@2.1.7
      fi
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels

install:
    - pip install -f travis-wheels/wheelhouse file://$PWD#egg=notebook[test]

script:
    - 'if [[ $GROUP == js* ]]; then travis_retry python -m notebook.jstest ${GROUP:3}; fi'
    - 'if [[ $GROUP == python ]]; then nosetests -v --with-coverage --cover-package=notebook notebook; fi'

matrix:
    include:
        - python: 3.3
          env: GROUP=python
        - python: 3.4
          env: GROUP=python

after_success:
    - codecov
