# miniconda bootstrap from conda-forge recipe
matrix:
  fast_finish: true

environment:
  matrix:
    - CONDA_PY: 35
      CONDA_INSTALL_LOCN: "C:\\Miniconda35-x64"
    - CONDA_PY: 27
      CONDA_INSTALL_LOCN: "C:\\Miniconda-x64"

platform:
  - x64

build: off

install:
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda update --yes --quiet conda
  - cmd: conda config --set show_channel_urls true
  - cmd: conda config --add channels conda-forge
  - cmd: conda install -y pyzmq tornado jupyter_client nbformat nbconvert ipykernel pip nodejs nose
  - cmd: pip install .[test]

test_script:
  - nosetests --exclude-dir notebook\terminal -v notebook
