name: notebook_docs
channels:
  - conda-forge
dependencies:
- python=3.8
- sphinx_rtd_theme
- jinja2
- tornado
- nbformat
- jupyter_client
- ipykernel
- pip
- sphinx
- terminado
- myst-parser
- nbclassic==0.4.5
- pip:
  - nbsphinx
  - Send2Trash
  - prometheus_client
  - sphinxcontrib_github_alt
  - ipython_genutils
