name: jupyterlab-classic
channels:
- conda-forge/label/jupyterlab_rc
- conda-forge/label/jupyterlab_server_rc
- conda-forge/label/jupyterlab_widgets_rc
- conda-forge
dependencies:
- ipywidgets=7
- jupyterlab=3
- jupyterlab_widgets=1
- matplotlib
- numpy
- nodejs
