name: 'Step 2: Publish Release'
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The target branch'
        required: false
      release_url:
        description: 'The URL of the draft GitHub release'
        required: false
      steps_to_skip:
        description: 'Comma separated list of steps to skip'
        required: false

jobs:
  publish_release:
    runs-on: ubuntu-latest
    permissions:
      # This is useful if you want to use PyPI trusted publisher
      # and NPM provenance
      id-token: write
    steps:
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@4b05d5f62ffa18bed92d556309c86a95554401b9 # v1

      - name: Populate Release
        id: populate-release
        uses: jupyter-server/jupyter_releaser/.github/actions/populate-release@035118abd7c9d96213f84a3db281cb2273758f00 # v2
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          branch: ${{ github.event.inputs.branch }}
          release_url: ${{ github.event.inputs.release_url }}
          steps_to_skip: ${{ github.event.inputs.steps_to_skip }}

      - name: Finalize Release
        id: finalize-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        uses: jupyter-server/jupyter-releaser/.github/actions/finalize-release@035118abd7c9d96213f84a3db281cb2273758f00 # v2
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          release_url: ${{ steps.populate-release.outputs.release_url }}

      - name: '** Next Step **'
        if: ${{ success() }}
        run: |
          echo "Verify the final release"
          echo ${{ steps.finalize-release.outputs.release_url }}

      - name: '** Failure Message **'
        if: ${{ failure() }}
        run: |
          echo "Failed to Publish the Draft Release Url:"
          echo ${{ steps.populate-release.outputs.release_url }}
